In [55]:
import pandas as pd
import numpy as np

def kpi(file_path):
    
    # Charger le fichier CSV dans un DataFrame : 
    df = pd.read_csv(file_path)
    
    #le temps de base heurs par jous: 
    tmp_base = 6
    #les heurs de fonctionnements heurs par jours : 
    temp_fjours = 12
    #nb de jours 
    #nombre_de_jours=31
    
    
    #Calculer le temps de maintenance predictive par min: 
    temps_main_predict = np.random.uniform(10, 30)*df['failure']
    
    #calculer le temps de maintenances corrective par min:
    temps_main_corr = np.random.uniform(15, 50)*df['realFail']
    #le temps supplimentaire :
    diff = df['failure']-df['realFail']
    #######
    List_jours2 =[31,29,31,30,31,30,31,31,30,31,30,31]
    for elem in List_jours2:
        temps_net = tmp_base*elem + (temps_main_predict/60 *elem)
        temps_brut = temps_net + (temps_main_corr/60 *elem)
    ######
    #calculer le temps net :
    #temps_net = tmp_base + temps_main_predict

    #calculer le temps brut : 
    #temps_brut = temps_net + temps_main_corr
        
       
    
    #calculer la productivité :
    
    rend = temps_net/temps_brut * 100
    
    #calcul des KPIs
    #calculer MTBF: nombre heurs de fonctionnement / nombre de pannes 
    List_jours =[31,29,31,30,31,30,31,31,30,31,30,31]
    for elements in List_jours:
        mtbf = temp_fjours*elements/df['realFail']
    
    
    #calculer MTTR : 
    
    mttr = temps_main_corr/df['realFail']
    
    #disponibilité materielle 
    dm = mtbf /(mtbf+mttr)
    
     # Ajouter les colonnes des KPIs au DataFrame
    df['temps_brut'] = temps_brut
    df['temps_net'] = temps_net
    df['productivite'] = rend
    df['mtbf'] = mtbf
    df['mttr'] = mttr
    df['disponibilité_materielle'] = dm
    
    # Enregistrer le nouveau fichier CSV avec les nouvelles colonnes
    new_file_path = file_path.split('.csv')[0] + '_with_kpisf.csv'
    df.to_csv(new_file_path, index=False)
    
    # Retourner le DataFrame avec les nouvelles colonnes
    return df

df_with_kpisf = kpi('results.csv')
df_with_kpisf

,month,failure,realFail,temps_brut,temps_net,productivite,mtbf,mttr,disponibilité_materielle
0,1,9,7,407.495607,325.242223,79.814903,53.142857,22.742871,0.700301
1,2,3,8,326.417942,232.414074,71.201378,46.500000,22.742871,0.671549
2,3,9,9,430.996574,325.242223,75.462833,41.333333,22.742871,0.645065
3,4,4,8,341.889300,247.885432,72.504589,46.500000,22.742871,0.671549
4,5,5,9,369.111142,263.356791,71.348914,41.333333,22.742871,0.645065
5,6,10,8,434.717449,340.713581,78.375870,46.500000,22.742871,0.671549
6,7,7,7,376.552891,294.299507,78.156220,53.142857,22.742871,0.700301
7,8,6,11,408.083467,278.828149,68.326255,33.818182,22.742871,0.597906
8,9,5,3,298.608241,263.356791,88.194750,124.000000,22.742871,0.845015
9,10,4,8,341.889300,247.885432,72.504589,46.500000,22.742871,0.671549
10,11,9,9,430.996574,325.242223,75.462833,41.333333,22.742871,0.645065
11,12,6,6,349.331050,278.828149,79.817740,62.000000,22.742871,0.731625

In [34]:
import pandas as pd
import numpy as np

def kpi(file_path):
    
    # Charger le fichier CSV dans un DataFrame : 
    df = pd.read_csv(file_path)
    
    #le temps de base heurs par jous: 
    tmp_base = 6
    #les heurs de fonctionnements heurs par jours : 
    temp_fjours = 12
    #nb de jours 
    #nombre_de_jours=31
    
    
    #Calculer le temps de maintenance predictive par min: 
   
        
  
    temps_main_predict = [np.random.uniform(10,30) for i in range(len(df))]*df['failure']
    #calculer le temps de maintenances corrective par min:
    temps_main_corr = [np.random.uniform(15, 50) for i in range(len(df))]*df['realFail']
    #le temps supplimentaire :
    diff = df['failure']-df['realFail']
    #######
    List_jours2 =[31,29,31,30,31,30,31,31,30,31,30,31]
    for elem in List_jours2:
        temps_net = tmp_base*elem + (temps_main_predict/60 *elem)
        temps_brut = temps_net + (temps_main_corr/60 *elem)
    ######
    #calculer le temps net :
    #temps_net = tmp_base + temps_main_predict

    #calculer le temps brut : 
    #temps_brut = temps_net + temps_main_corr
        
       
    
    #calculer la productivité :
    
    rend = temps_net/temps_brut * 100
    
    #calcul des KPIs
    #calculer MTBF: nombre heurs de fonctionnement / nombre de pannes 
    List_jours =[31,29,31,30,31,30,31,31,30,31,30,31]
    for elements in List_jours:
        mtbf = temp_fjours*elements/df['realFail']
    
    
    #calculer MTTR : 
    
    mttr = temps_main_corr/df['realFail']
    
    #disponibilité materielle 
    dm = mtbf /(mtbf+mttr)
    
     # Ajouter les colonnes des KPIs au DataFrame
    df['temps_brut'] = temps_brut
    df['temps_net'] = temps_net
    df['productivite'] = rend
    df['mtbf'] = mtbf
    df['mttr'] = mttr
    df['disponibilité_materielle'] = dm
    
    # Enregistrer le nouveau fichier CSV avec les nouvelles colonnes
    new_file_path = file_path.split('.csv')[0] + '_with_kpisf.csv'
    df.to_csv(new_file_path, index=False)
    
    # Retourner le DataFrame avec les nouvelles colonnes
    return df
#print(kpi('results.csv'))
df_with_kpisf = kpi('results.csv')
df_with_kpisf

,month,failure,realFail,temps_brut,temps_net,productivite,mtbf,mttr,disponibilité_materielle
0,1,9,7,416.855466,274.326852,65.808625,53.142857,39.408833,0.574197
1,2,3,8,304.609807,230.016221,75.511758,46.500000,18.046835,0.720407
2,3,9,9,444.344865,282.354805,63.544068,41.333333,34.836572,0.542647
3,4,4,8,293.073200,222.982197,76.084131,46.500000,16.957501,0.732774
4,5,5,9,438.586764,231.200472,52.714877,41.333333,44.599203,0.480997
5,6,10,8,421.868923,289.458039,68.613264,46.500000,32.034891,0.592094
6,7,7,7,399.279969,251.706503,63.040103,53.142857,40.803723,0.565671
7,8,6,11,507.134538,249.894902,49.275859,33.818182,45.262106,0.427644
8,9,5,3,300.313741,256.951168,85.560909,124.000000,27.975854,0.815919
9,10,4,8,355.142731,234.091526,65.914773,46.500000,29.286582,0.613565
10,11,9,9,480.014728,323.752624,67.446394,41.333333,33.604753,0.551566
11,12,6,6,313.994017,259.699441,82.708404,62.000000,17.514379,0.779733

In [44]:
import pandas as pd
import numpy as np

def kpi(file_path):
    
    # Charger le fichier CSV dans un DataFrame : 
    df = pd.read_csv(file_path)
    
    #le temps de base heurs par jous: 
    tmp_base = 6
    #les heurs de fonctionnements par jours : 
    temp_fjours = 12
    
    
    #Calculer le temps de maintenance predictive : 
    temps_main_predict = [np.random.uniform(10,30) for i in range(len(df))] * df['failure']
    
    #calculer le temps de maintenances corrective :
    temps_main_corr = [np.random.uniform(15, 50) for i in range(len(df))] * df['realFail']
    
    #calculer le temps net :
   
    List_jours2 =[31,29,31,30,31,30,31,31,30,31,30,31]
    for elem in List_jours2:
        temps_net = tmp_base*elem + (temps_main_predict/60 *elem)
   
    #calculer le temps brut : 
    
    diff = df['failure']-df['realFail']
    rend = [i for i in range(len(diff))]
    rend = np.array(rend)
    temps_brut = [i for i in range(len(diff))]
    temps_brut = np.array(temps_brut)
    for i in range(len(diff)):
        
            if (diff[i]==0) :  
                for elem in List_jours2:
                    temps_brut[i]=temps_net[i] + (temps_main_corr[i]/60 *elem)
                rend[i]= (temps_net[i]/temps_brut[i] )*100
            elif (diff[i]>0):
                for elem in List_jours2:
                    temps_brut[i]=temps_net[i] + (temps_main_predict[i]/60 *elem)
                rend[i]= (temps_net[i]/temps_brut[i] )*100
            elif (diff[i]<0):
                #calculer le temps brut : 
                for elem in List_jours2:
                    temps_brut[i] = temps_net[i] + (temps_main_corr[i]/60 *elem)
                rend[i]=(temps_net[i]/temps_brut[i])*100
        
    
    #calcul des KPIs
    #calculer MTBF: nombre heures de fonctionnement / nombre de pannes 
    
   # mtbf = temp_fjours*nombre_de_jours/df['realFail']
    List_jours =[31,29,31,30,31,30,31,31,30,31,30,31]
    for elements in List_jours:
        mtbf = temp_fjours*elements/df['realFail']
    
    
    #calculer MTTR : 
    
    mttr = temps_main_corr/df['realFail']
    
    #disponibilité materielle 
    dm = mtbf /(mtbf+mttr)
    
     # Ajouter les colonnes des KPIs au DataFrame
    df['temps_fonctionnement_parJ'] = temp_fjours
    df['temps_utile/inutile'] = diff
    df['temps_brut'] = temps_brut
    df['temps_net'] = temps_net
    df['productivite'] = rend
    
    df['mtbf'] = mtbf
    df['mttr'] = mttr
    df['disponibilité_materielle'] = dm
    
    # Enregistrer le nouveau fichier CSV avec les nouvelles colonnes
    new_file_path = file_path.split('.csv')[0] + '_with_kpisfs33.csv'
    df.to_csv(new_file_path, index=False)
    
    # Retourner le DataFrame avec les nouvelles colonnes
    return df

df_with_kpisf33 = kpi('results.csv')
df_with_kpisf33

hh
hh
hh
hh
hh
hh
hh
cc
cc
cc
hh
hh

,month,failure,realFail,temps_fonctionnement_parJ,temps_utile/inutile,temps_brut,temps_net,productivite,mtbf,mttr,disponibilité_materielle
0,1,6,11,12,-5,369,247.283286,67,33.818182,21.519033,0.611129
1,2,6,9,12,-3,472,242.326360,51,41.333333,49.521539,0.454938
2,3,4,6,12,-2,314,216.074368,68,62.000000,31.728934,0.661482
3,4,4,9,12,-5,416,230.804011,55,41.333333,40.008203,0.508145
4,5,6,11,12,-5,423,245.085757,57,33.818182,31.324643,0.519139
5,6,5,9,12,-4,377,260.094756,68,41.333333,25.271648,0.620574
6,7,5,7,12,-2,327,221.254834,67,53.142857,29.252684,0.644972
7,8,12,8,12,4,331,258.946821,78,46.500000,33.912967,0.578265
8,9,16,15,12,1,459,322.514433,70,24.800000,39.006346,0.388676
9,10,11,4,12,7,482,334.361444,69,93.000000,25.124010,0.787308
10,11,4,6,12,-2,324,227.532814,70,62.000000,31.289161,0.664600
11,12,2,8,12,-6,396,197.788847,49,46.500000,48.070875,0.491695