In [4]:
import pandas as pd
import numpy as np


df = pd.read_csv('results.csv')

# Convertir la colonne 'month' en type datetime pour facilité les calcules 
df['month'] = pd.to_datetime(df['month'])

# Ajouter une colonne pour le temps brut de fonctionnement pour facilité la visualisation en csv
df['temps_brut'] = df['failure'] + df['realFail']

# Ajouter une colonne pour le temps net de fonctionnement pour facilité la visualisation des données en csv 
df['temps_net'] = df['realFail']

# Définir le temps brut de fonctionnement à atteindre pour chaque mois
temps_brut_objectif = 300

# Calculer le temps net de fonctionnement pour chaque mois
df_temps_net = df.groupby(df['month'].dt.month)['temps_net'].sum()

# Calculer le temps brut de fonctionnement pour chaque mois
df_temps_brut = df.groupby(df['month'].dt.month)['temps_brut'].sum()

# Calculer la productivité pour chaque mois
df_productivite = df_temps_net / df_temps_brut * temps_brut_objectif

# Afficher les résultats
print(df_temps_net)
print(df_temps_brut)
print(df_productivite)

month
1    93
Name: temps_net, dtype: int64
month
1    170
Name: temps_brut, dtype: int64
month
1    164.117647
dtype: float64

In [5]:
# Ajouter une colonne pour le temps brut de fonctionnement
df['temps_brut'] = df['failure'] + df['realFail']

# Ajouter une colonne pour le temps net de fonctionnement
df['temps_net'] = df['realFail']

# Enregistrer les données dans un nouveau fichier CSV
df.to_csv('nouveau_nom_fichier.csv', index=False)

In [7]:
import pandas as pd
import numpy as np

# Lire les données à partir d'un fichier CSV
df = pd.read_csv('results.csv')

# Convertir la colonne 'month' en type datetime
df['month'] = pd.to_datetime(df['month'])

# Ajouter une colonne pour le temps brut de fonctionnement
df['temps_brut'] = df['failure'] + df['realFail']

# Ajouter une colonne pour le temps net de fonctionnement
df['temps_net'] = 6 + df['realFail']

# Définir le temps brut de fonctionnement à atteindre pour chaque mois
temps_brut_objectif = 300

# Calculer le temps net de fonctionnement pour chaque mois
df_temps_net = df.groupby(df['month'].dt.month)['temps_net'].sum()

# Calculer le temps brut de fonctionnement pour chaque mois
df_temps_brut = df.groupby(df['month'].dt.month)['temps_brut'].sum()

# Calculer la productivité pour chaque mois
df_productivite = df_temps_net / df_temps_brut * temps_brut_objectif

# Afficher les résultats
print(df_temps_net)
print(df_temps_brut)
print(df_productivite)

month
1    165
Name: temps_net, dtype: int64
month
1    170
Name: temps_brut, dtype: int64
month
1    291.176471
dtype: float64

In [9]:
import pandas as pd

def calculate_kpis(file_path, temps_base):
    # Charger le fichier CSV dans un DataFrame
    df = pd.read_csv(file_path)
    
    # Calculer le temps brut de fonctionnement (en heures)
    temps_brut = df['failure'] + df['realFail']
    
    # Calculer le temps net de fonctionnement (en heures)
    temps_maintenance_predictive = df['realFail']
    temps_net = temps_base + temps_maintenance_predictive
    
    # Calculer la productivité
    productivite = temps_net / temps_brut * 100
    
    # Ajouter les colonnes des KPIs au DataFrame
    df['temps_brut'] = temps_brut
    df['temps_net'] = temps_net
    df['productivite'] = productivite
    
    # Enregistrer le nouveau fichier CSV avec les nouvelles colonnes
    new_file_path = file_path.split('.csv')[0] + '_with_kpis.csv'
    df.to_csv(new_file_path, index=False)
    
    # Retourner le DataFrame avec les nouvelles colonnes
    return df

In [10]:
print('results.csv',6)

results.csv 6

In [11]:
df_with_kpis = calculate_kpis('results.csv', 6)

les kpis MTBF et MTTR

In [22]:
import pandas as pd

def calculate_kpis(file_path, temps_base):
    # Charger le fichier CSV dans un DataFrame
    df = pd.read_csv(file_path)
    
    # Calculer le temps brut de fonctionnement par heures
    temps_brut = df['failure'] + df['realFail']
    
    # Calculer le temps net de fonctionnement oar heures
    temps_maintenance_predictive = df['realFail']
    temps_net = temps_base + temps_maintenance_predictive
    
    # Calculer la productivité
    productivite = temps_net / temps_brut * 100
    
    # MTBF en heures    
    temps_entre_pannes = temps_brut.diff().shift(-1)
    temps_entre_pannes.iloc[-1] = temps_brut.iloc[-1]
    mtbf = temps_entre_pannes.mean()
    
    # MTTR en heures
    mttr = df['realFail'].mean()
    
    # Ajouter les colonnes des KPIs au DataFrame
    df['temps_brut'] = temps_brut
    df['temps_net'] = temps_net
    df['productivite'] = productivite
    df['mtbf'] = mtbf
    df['mttr'] = mttr
    
    # Enregistrer le nouveau fichier CSV avec les nouvelles colonnes
    new_file_path = file_path.split('.csv')[0] + '_with_kpis2.csv'
    df.to_csv(new_file_path, index=False)
    
    # Retourner le DataFrame avec les nouvelles colonnes
    return df

In [23]:
df_with_kpis2 = calculate_kpis('results.csv', 6)

In [24]:
df_with_kpis2

,month,failure,realFail,temps_brut,temps_net,productivite,mtbf,mttr
0,1,9,7,16,13,81.250000,0.666667,7.75
1,2,3,8,11,14,127.272727,0.666667,7.75
2,3,9,9,18,15,83.333333,0.666667,7.75
3,4,4,8,12,14,116.666667,0.666667,7.75
4,5,5,9,14,15,107.142857,0.666667,7.75
5,6,10,8,18,14,77.777778,0.666667,7.75
6,7,7,7,14,13,92.857143,0.666667,7.75
7,8,6,11,17,17,100.000000,0.666667,7.75
8,9,5,3,8,9,112.500000,0.666667,7.75
9,10,4,8,12,14,116.666667,0.666667,7.75
10,11,9,9,18,15,83.333333,0.666667,7.75
11,12,6,6,12,12,100.000000,0.666667,7.75